[package]
name = "bens_number_theory"
version = "0.3.4"
edition = "2021"
authors = ["Ben10164"]
description = "A sample Rust project for number theory stuff (im using this to learn rust)"
license = "MIT OR Apache-2.0"
keywords = ["testing", "beginner", "number-theory"]
