[package]
name = "bens_number_theory"
version = "0.2.2"
edition = "2021"
authors = ["Ben10164 <benpuryear@hotmail.com>"]
description = "A sample Rust project for calculating prime numbers"
license = "MIT OR Apache-2.0"
keywords = ["rust", "testing", "beginner", "prime"]
