[package]
name = "bens_is_prime"
version = "0.2.1"
edition = "2021"
authors = ["Ben Puryear <benpuryear@hotmail.com>"]
description = "A sample Rust project for calculating prime numbers"
license = "MIT OR Apache-2.0"
keywords = ["rust", "testing", "beginner", "prime"]
